"""Article figures for the dolphin self-repeat paper. PNG 300 dpi + PDF into figures/.

Code name → article figure mapping (after renumbering):
  fig5 → Fig 1  example bouts: contour overlays + one real-time sequence         (features.pkl contours)
  fig1 → Fig 2  exact vs transposed triangles, both nulls, per-session replication (d04_triangles.json)
  fig3 → Fig 3  pitch invariance: P(shape match | |df|) at long lag vs short lag   (d04_renull.json)
  fig2 → Fig 4  gap-resolved exact-pair excess, within-minute null                 (d04_renull.json)
  fig4 → Fig 5  threshold sweep of the excess pair count                           (d04_threshold.json)
Cross-species figures (Fig 6–8) are generated by marmoset/m06_crossspecies.py.
Style: shared figstyle.py. Species colour is fixed across all article figures: dolphin = orange (observed/exact),
darker burnt orange for the secondary dolphin series (transposed), nulls = neutral greys. All figures 10 in wide,
12 pt labels / 10 pt ticks, PNG 300 dpi + vector PDF.
"""
import json, numpy as np
import matplotlib; matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.patches import Patch
from matplotlib.lines import Line2D
import sys
from d01_lib import *
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
from figstyle import *          # palette, type scale, style(), panel_label(), save_both() -- shadows d01_lib.style
J = lambda n: json.load(open(os.path.join(OUT, n)))
tri = J('d04_triangles.json'); rn = J('d04_renull.json'); th = J('d04_threshold.json')


def out(f, name):
    save_both(f, FIG, name)


# ================= Figure 1: triangles =================
f, (a, b) = plt.subplots(1, 2, figsize=(FULL_W, 4.6), gridspec_kw=dict(width_ratios=[1.35, 1], wspace=0.38))
style(a, ylabel='mutually-exact triples within 10 s')
groups = [('exact', 'Same pitch\n(DTW-abs ≤ p5)'), ('shifted', 'Transposed > 1 kHz\n(DTW-shape ≤ p5)')]
w = 0.26; xs = np.array([0, 1.15])
rng = np.random.default_rng(1)
for gi, (k, lab) in enumerate(groups):
    r = tri[k]; x0 = xs[gi]
    vals = [(r['obs'], 0, DOLPHIN if k == 'exact' else DOLPHIN_DARK, 'observed'), (r['session']['null_mean'], r['session']['null_sd'], G1, 'null: session'),
            (r['file']['null_mean'], r['file']['null_sd'], G2, 'null: within-minute')]
    for bi, (v, sd, c, _) in enumerate(vals):
        x = x0 + (bi - 1) * w
        a.bar(x, v, w - 0.03, color=c, edgecolor=SURF, linewidth=1, zorder=2)
        if sd: a.errorbar(x, v, yerr=2 * sd, color=INK, capsize=2, lw=0.8, zorder=4)
        # per-session dots
        ps = r['per_session_obs'] if bi == 0 else (r['session'] if bi == 1 else r['file'])['per_session_null']
        pv = np.array([ps[s] for s in r['per_session_obs']], float); pv = pv[pv > 0]
        a.scatter(x + rng.uniform(-0.06, 0.06, len(pv)), pv, s=10, color=INK, alpha=0.45, lw=0, zorder=5)
    a.text(x0 - w, r['obs'] + 45, f"{r['obs']:,}", ha='center', color=INK, fontsize=FS_ANNO)
    a.text(x0, r['session']['null_mean'] + 2 * r['session']['null_sd'] + 45, f"{r['session']['null_mean']:.0f}", ha='center', color=INK2, fontsize=FS_SMALL)
    a.text(x0 + w, r['file']['null_mean'] + 2 * r['file']['null_sd'] + 45, f"{r['file']['null_mean']:.0f}", ha='center', color=INK2, fontsize=FS_SMALL)
    ratio_s = r['obs'] / r['session']['null_mean']; ratio_f = r['obs'] / r['file']['null_mean']
    a.text(x0 - w / 2 + 0.02 if k == 'exact' else x0, 980 if k == 'exact' else 480, f"{ratio_f:.2f}× within-minute (z = {r['file']['z']:.1f})\n{ratio_s:.2f}× session (z = {r['session']['z']:.0f})",
           ha='left' if k == 'exact' else 'center', va='bottom', color=INK2, fontsize=FS_SMALL, linespacing=1.3)
a.set_xticks(xs); a.set_xticklabels([g[1] for g in groups]); a.set_ylim(0, 1750); a.set_xlim(-0.5, 1.65)
f.legend(handles=[Patch(color=DOLPHIN, label='observed, same pitch'), Patch(color=DOLPHIN_DARK, label='observed, transposed'), Patch(color=G1, label='null: onset permutation within session'),
                  Patch(color=G2, label='null: onset permutation within 1-min file'), Line2D([], [], marker='o', ls='', color=INK, alpha=0.5, ms=4, label='per session (n = 19); zero counts plotted at 0.25 in b')],
         loc='upper center', bbox_to_anchor=(0.5, -0.04), ncol=2, handlelength=1.2, columnspacing=1.5)
panel_label(a, 'a')
# (b) per-session replication, log-log
style(b, xlabel='within-minute null\n(mean of 200 draws)', ylabel='observed')
lim = [0.15, 2000]; b.plot(lim, lim, color=G2, lw=0.8, ls='--', zorder=1)
for k, c, lab in [('exact', DOLPHIN, 'same pitch'), ('shifted', DOLPHIN_DARK, 'transposed')]:
    r = tri[k]; o = np.array([r['per_session_obs'][s] for s in r['per_session_obs']], float); n = np.array([r['file']['per_session_null'][s] for s in r['per_session_obs']], float)
    m = (o > 0) | (n > 0); o = np.maximum(o[m], 0.25); n = np.maximum(n[m], 0.25)
    b.scatter(n, o, s=26, color=c, alpha=0.85, lw=0.5, edgecolor=SURF, zorder=3, label=f"{lab}:\n{r['file']['sessions_gt']} of {r['file']['sessions_tested']} above null")
b.set_xscale('log'); b.set_yscale('log'); b.set_xlim(lim); b.set_ylim(lim)
for setter, lab in [(b.set_xticks, b.set_xticklabels), (b.set_yticks, b.set_yticklabels)]:
    setter([0.25, 1, 10, 100, 1000]); lab(['0', '1', '10', '100', '1000'])
b.xaxis.set_minor_locator(matplotlib.ticker.NullLocator()); b.yaxis.set_minor_locator(matplotlib.ticker.NullLocator())
b.legend(loc='upper left', labelspacing=0.8, handletextpad=0.3, borderaxespad=0.1, facecolor=SURF, framealpha=0.9, frameon=True, edgecolor='none'); panel_label(b, 'b')
headline(f, 'Mutually-exact whistle triples are 2.5× chance; transposed triples are at chance', y=1.03)
out(f, 'article_fig1')

# ================= Figure 2: gap-resolved excess =================
f, a = plt.subplots(figsize=(FULL_W, 5.4)); style(a, ylabel='exact pairs: observed / null', xlabel='gap between end of first and onset of second whistle')
g = rn['gap']['table']; x = np.arange(len(g))
a.axvspan(-0.5, 1.5, color=BAND_NEUTRAL, zorder=0); a.axvspan(1.5, 3.5, color=BAND_WARM, zorder=0)
a.text(0.5, 2.17, '< 1 s: multi-loop / response window', ha='center', va='top', fontsize=FS_SMALL, color=INK2, zorder=5, bbox=dict(fc=BAND_NEUTRAL, ec='none', pad=2))
a.text(2.5, 2.17, '1–10 s: SIGID signature-bout window', ha='center', va='top', fontsize=FS_SMALL, color=INK2, zorder=5, bbox=dict(fc=BAND_WARM, ec='none', pad=2))
a.axhline(1, color=G2, lw=0.8, ls='--', zorder=1)
for name, c, lab, off, ms, lw, al in [('session', G2, 'null: within session', -0.12, 5, 0.8, 0.7), ('file', DOLPHIN, 'null: within 1-min file', 0.08, 8, 1.4, 1.0)]:
    y = np.array([r[f'ratio_{name}'] for r in g]); ci = np.array([r[f'ratio_{name}_ci'] for r in g])
    a.errorbar(x + off, y, yerr=[y - ci[:, 0], ci[:, 1] - y], fmt='o', color=c, ms=ms, capsize=3 if name == 'file' else 0, lw=lw, zorder=3, alpha=al, label=lab)
    a.plot(x + off, y, color=c, lw=1.8 if name == 'file' else 1.0, zorder=2, alpha=0.9 if name == 'file' else 0.6)
for i, r in enumerate(g):
    a.text(i + 0.08 + 0.09, r['ratio_file'], f"{r['ratio_file']:.2f}", ha='left', va='center', fontsize=FS_ANNO, color=INK)
    a.text(i, 0.52, f"n = {r['n']:,}\n+{r['excess_file']:.0f} pairs\n{r['sessions_gt_file']}/{r['sessions_tested_file']} sessions", ha='center', va='bottom', fontsize=FS_SMALL, color=INK2)
a.set_xticks(x); a.set_xticklabels(['0–0.25 s', '0.25–1 s', '1–3 s', '3–10 s']); a.set_ylim(0.5, 2.2); a.set_xlim(-0.5, 3.5)
a.legend(loc='lower left', bbox_to_anchor=(0.0, 0.17))
headline(f, 'Exact-repeat excess decays smoothly with gap — one process, not two', y=0.97)
out(f, 'article_fig2')

# ================= Figure 3: pitch invariance =================
f, (a, b) = plt.subplots(1, 2, figsize=(FULL_W, 4.4), sharey=True, gridspec_kw=dict(wspace=0.12))
ct = rn['conditional']; x = np.arange(len(ct)); labs = ['0–0.5', '0.5–1', '1–2', '2–3', '3–5', '5–15']
style(a, xlabel='|Δ mean frequency| of the pair (kHz)', ylabel='P(shape match | Δf)\n(DTW-shape ≤ p5)')
style(b, xlabel='|Δ mean frequency| of the pair (kHz)')
pl = np.array([r['p_long'] for r in ct])
a.plot(x, pl, color=G3, lw=1.8, marker='o', ms=6, zorder=3, label='pairs 60–600 s apart (n = 547k)')
a.axhline(pl.mean(), color=G2, lw=0.8, ls='--', zorder=1); a.text(1.5, pl.mean() + 0.0012, f'mean {pl.mean():.3f}', ha='center', va='bottom', fontsize=FS_SMALL, color=INK2)
a.set_title('60–600 s apart: any shape at any pitch', loc='left', fontsize=FS_LABEL); a.legend(loc='lower left'); panel_label(a, 'a')
ps = np.array([r['p_short'] for r in ct]); ci = np.array([r['p_short_ci'] for r in ct]); pn = np.array([r['p_null_file'] for r in ct]); pns = np.array([r['p_null_file_sd'] for r in ct])
b.fill_between(x, pn - 2 * pns, pn + 2 * pns, color=G1, alpha=0.5, lw=0, zorder=1, label='null: within-minute permutation (±2 sd)')
b.plot(x, pn, color=G2, lw=1, zorder=2)
b.errorbar(x, ps, yerr=[ps - ci[:, 0], ci[:, 1] - ps], fmt='o', color=DOLPHIN, ms=7, capsize=3, lw=1.2, zorder=4, label='observed pairs ≤ 10 s apart (n = 34k)')
b.plot(x, ps, color=DOLPHIN, lw=1.8, zorder=3)
for i in [0, 1]:
    b.text(i, ci[i, 1] + 0.0015, f"{ct[i]['ratio_file']:.2f}×", ha='center', fontsize=FS_ANNO, color=INK)
b.set_title('≤ 10 s apart: excess only at the same pitch', loc='left', fontsize=FS_LABEL); b.legend(loc='lower left'); panel_label(b, 'b')
for ax in (a, b): ax.set_xticks(x); ax.set_xticklabels(labs); ax.set_ylim(0.030, 0.080)
headline(f, 'The population transposes freely; the individual, within a bout, does not', y=1.04)
out(f, 'article_fig3')

# ================= Figure 4: threshold sweep =================
f, (a, b) = plt.subplots(2, 1, figsize=(FULL_W, 6.8), sharex=True, gridspec_kw=dict(height_ratios=[2, 1], hspace=0.22))
rows = th['rows']; pc = np.array([r['pct'] for r in rows], float)
ex = np.array([r['excess_pairs_file'] for r in rows]); sd = np.array([r['null_pairs_file_sd'] for r in rows])
exs = np.array([r['excess_pairs_session'] for r in rows])
style(a, ylabel='excess exact pairs\nwithin 10 s (obs − null)')
a.fill_between(pc, ex - 2 * sd, ex + 2 * sd, color=DOLPHIN, alpha=0.15, lw=0)
a.plot(pc, ex, color=DOLPHIN, lw=2.2, marker='o', ms=6, zorder=3, label='null: within 1-min file')
a.plot(pc, exs, color=G2, lw=1.2, marker='o', ms=4.5, zorder=2, alpha=0.8, label='null: within session')
a.axvline(5, color=G2, lw=0.8, ls='--'); a.text(5.6, 1420, 'p5 = reporting threshold', fontsize=FS_SMALL, color=INK2, va='top')
imax = int(np.argmax(ex)); a.axhline(ex[imax], color=DOLPHIN, lw=0.8, ls=':', zorder=1)
a.text(40, ex[imax] + 25, f'plateau ≈ {ex[imax]:.0f} pairs (p20–p30)', ha='center', va='bottom', fontsize=FS_ANNO, color=INK)
a.text(5.8, ex[pc == 5][0] - 110, f'{ex[pc == 5][0]:.0f} at p5', fontsize=FS_ANNO, color=INK)
a.set_ylim(0, 1450); a.legend(loc='lower right'); panel_label(a, 'a')
headline(f, 'Excess repeat pairs vs. exactness threshold: steep to p10, flat by p15–p30', y=0.96)
style(b, xlabel='DTW-abs threshold (percentile of all within-session pair distances)', ylabel='marginal gain\n(pairs / pct point)')
mg = np.array([r['marginal_excess_per_pct'] for r in rows]); mgs = np.array([r['marginal_excess_per_pct_sd'] for r in rows])
b.axhline(0, color=G2, lw=0.8, ls='--')
b.errorbar(pc, mg, yerr=mgs, fmt='o', color=DOLPHIN, ms=5.5, capsize=3, lw=1.2, zorder=3); b.plot(pc, mg, color=DOLPHIN, lw=1.6, zorder=2)
b.set_ylim(-45, 145); b.set_xlim(0, 52); b.set_xticks([1, 5, 10, 20, 30, 40, 50]); panel_label(b, 'b')
out(f, 'article_fig4')

# ================= Figure 5: example bouts =================
df, F = load(); C = F['C']
def sess_tag(w):                  # session number + recording date, read from the data (not hand-typed)
    d = str(int(df.date.values[w])); return f"session {int(df.session.values[w])} ({d[:4]}-{d[4:6]}-{d[6:]})"


bouts = [('Rise', [264, 271, 273]), ('U', [2349, 2351, 2353]), ('Arch', [4472, 4481, 4487, 4492, 4497])]
bouts = [(f'{name} — {sess_tag(ix[0])}' + (f', {len(ix)} renditions' if len(ix) > 3 else ''), ix) for name, ix in bouts]
seq = [3987, 3988, 3989, 3990, 3991, 3992, 3993, 3994, 3995]
f = plt.figure(figsize=(FULL_W, 7.8)); gs = f.add_gridspec(2, 3, height_ratios=[1.35, 1], hspace=0.5, wspace=0.3)
for k, (title, ix) in enumerate(bouts):
    ax = f.add_subplot(gs[0, k]); style(ax, xlabel='time from whistle onset (s)', ylabel='frequency (kHz)' if k == 0 else None)
    t0s = df.abs_t0.values[ix]; cols = BLUES[:len(ix)] if len(ix) <= 3 else BLUES
    if len(ix) == 3: cols = [BLUES[0], BLUES[2], BLUES[4]]
    for i, (w, c) in enumerate(zip(ix, cols)):
        a_ = C[w]; ax.plot(a_[:, 0] - a_[0, 0], a_[:, 1] / 1000, color=c, lw=2, alpha=0.95, label=f'+{t0s[i] - t0s[0]:.1f} s' if i else '0 s')
    ax.set_title(title, loc='left', fontsize=FS_ANNO); ax.legend(title='onset', loc='best', handlelength=1.2, fontsize=FS_SMALL)
    ax.set_ylim(min(C[w][:, 1].min() for w in ix) / 1000 - 1, max(C[w][:, 1].max() for w in ix) / 1000 + 1)
    panel_label(ax, 'abc'[k])
# (d) the real-time sequence
ax = f.add_subplot(gs[1, :]); style(ax, xlabel=f'time (s) — {sess_tag(seq[0])}, one-minute file', ylabel='frequency (kHz)')
t_ref = df.abs_t0.values[seq[0]]
thr = tri['thr_abs']; Da = np.load(os.path.join(OUT, 'dtw_abs.npy'))
for w in seq:
    a_ = C[w]; is_arch = df.cls.astype(str).values[w] == 'arch'
    ax.plot(df.file_start.values[w] + a_[:, 0] - t_ref, a_[:, 1] / 1000, color=DOLPHIN if is_arch else G3, lw=2)
ax.text(df.abs_t0.values[3992] - t_ref + 0.35, 14.3, 'U — not exact to any arch', fontsize=FS_SMALL, color=G3, va='bottom', ha='center')
n_ex = int((Da[np.ix_(seq, seq)] <= thr).sum() - len(seq)) // 2
ax.set_title(f'Eight arch renditions in 31 s, {n_ex} of 28 arch pairs exact (DTW-abs ≤ p5); one U interleaved', loc='left', fontsize=FS_ANNO)
ax.set_ylim(4, 16); ax.set_xlim(-1, 32); panel_label(ax, 'd')
headline(f, 'Example bouts: the same contour at the same absolute frequency, seconds apart', y=0.965)
out(f, 'article_fig5')
